<?php

/**
 * @file
 * This is used for redirecting the user after login.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_id_alter().
 */
function myblock_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'user_login_form') {
    $form['#submit'][] = 'myblock_user_login_form_submit';
  }

}

/**
 * Custom submit handler for login form.
 */
function myblock_user_login_form_submit($form, FormStateInterface $form_state) {
  $request = \Drupal::service('request_stack')->getCurrentRequest();
  $request->query->set('destination', '/custom-welcome-page');
}
